# Generated by Django 3.1.4 on 2022-06-29 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Start Time'),
            preserve_default=False,
        ),
    ]
