# Generated by Django 3.1.4 on 2022-06-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8, verbose_name='Duration'),
            preserve_default=False,
        ),
    ]
