# Generated by Django 3.1.4 on 2022-07-04 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=8, verbose_name='Duration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Start Time'),
        ),
    ]
