# Generated by Django 3.1.4 on 2022-07-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220704_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Count'),
        ),
    ]
