# Generated by Django 3.1.4 on 2022-07-04 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220704_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
    ]
