# Generated by Django 3.1.4 on 2022-07-04 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220704_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Start Time'),
        ),
    ]
