# Generated by Django 3.1.4 on 2022-07-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220704_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.TextField(blank=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='product',
            name='person',
            field=models.TextField(blank=True, verbose_name='Person'),
        ),
    ]
